# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: macogurumi
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: macogurumi
service: macogurumi-backend

plugins:
  - serverless-offline
  - serverless-dynamodb

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  main:
    handler: dist/main.handler
    timeout: 30  # Set the timeout to 30 seconds
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

package:
  excludeDevDependencies: true
  patterns:
    - 'dist/main.js'
    - '!.vercel/**'
    - '!node_modules/**'
    - '!src/**'
    - '!test/**'           
    - '!nest-cli.json'
    - '!package.json'
    - '!README.md'
    - '!template.yml'
    - '!tsconfig.build.json'
    - '!tsconfig.json'
    - '!vercel.json'
    - '!webpack.config.js'
    - '!yarn.lock'
    - '!.dynamodb/**'
